version: "3.4"

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    depends_on:
      - backend
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./backend/storage/app/public/uploads:/var/www/uploads
  web:
    container_name: ${APP_NAME}-web
    restart: always
    build:
      context: ./web
      dockerfile: ../docker/web/Dockerfile
    networks:
      - app-network
  admin:
    container_name: ${APP_NAME}-admin
    restart: always
    build:
      context: ./
      dockerfile: ./docker/admin/Dockerfile
    networks:
      - app-network
  admin-auth:
    container_name: ${APP_NAME}-admin-auth
    restart: always
    build:
      context: ./docker/admin-auth
      dockerfile: Dockerfile
    environment:
      PAGE_TITLE: ${APP_TITLE} - Dev
      BASE_PATH: /admin/auth
      IS_LOGO_PNG: {{CONFIG_IS_LOGO_PNG}}
      LANGUAGE: "{{CONFIG_LANGUAGE}}"
      BRAND_COLOR: "{{CONFIG_BRAND_COLOR}}"
    networks:
      - app-network
  backend:
    container_name: ${APP_NAME}-backend
    restart: always
    working_dir: /var/www
    tty: true
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: dev
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/var/www/app
    environment:
      CONTAINER_ROLE: fpm
      WEB_DOCUMENT_ROOT: /var/www/app/public
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 18000
    networks:
      - app-network
  db:
    container_name: ${APP_NAME}-db
    image: mysql:5.7
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app-network
  redis:
    image: redis
    container_name: ${APP_NAME}-redis
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

