version: "3.4"

services:
  backend:
    container_name: ${APP_NAME}-backend
    restart: always
    working_dir: /var/www/app
    tty: true
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: production
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./backend/storage:/var/www/app/storage
    extra_hosts:
      - "dockerhost:${LOCAL_IP}"
    environment:
      CONTAINER_ROLE: fpm
      WEB_DOCUMENT_ROOT: /var/www/app/public
      PHP_MEMORY_LIMIT: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 18000dc
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


