version: "3.4"

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www
    networks:
      - app-network
  web:
    container_name: ${APP_NAME}-web
    restart: always
    build:
      context: ./web
      dockerfile: ./docker/web/Dockerfile
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

