version: "3.3"

services:
  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    depends_on:
      - api
    working_dir: /var/www
    networks:
      - app-network
  admin:
    container_name: ${APP_NAME}-admin
    restart: always
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    networks:
      - app-network
  admin-auth:
    container_name: ${APP_NAME}-admin-auth
    restart: always
    image: ozitag/tvixer-admin-auth
    networks:
      - app-network
  api:
    container_name: ${APP_NAME}-api
    restart: always
    working_dir: /var/www
    tty: true
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - db
    environment:
      CONTAINER_ROLE: fpm
      WEB_DOCUMENT_ROOT: /var/www/app/public
      PHP_MEMORY_LIMIT: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 18000
    networks:
      - app-network
  db:
    container_name: ${APP_NAME}-db
    image: mysql:5.7
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


